version: '3.8'
services:
   backend:
    image: sudheer007dfs/backend-assignment
    container_name: backend-server
    ports:
      - "8000:8000"  
    environment:
      - MONGODB_URI=${MONGODB_URI}
