version: '3.8'
services:
   backend:
    image: sudheer007dfs/backend-assignment1:v1
    container_name: backend-server
    environment:
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "8080:8080"